version: '2.2'
services:
  app:
    image: k8s.gcr.io/echoserver:1.4
    container_name: app
    user: root
    labels:
      co.elastic.metrics/enabled: true
      co.elastic.metrics/module: system
      co.elastic.metrics/period: 1m
    networks:
      - echoapp
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/
    user: root
    labels:
      co.elastic.metrics/enabled: true
      co.elastic.metrics/module: nginx
      co.elastic.metrics/hosts: '$${data.host}:80'
      co.elastic.metrics/period: 1m
      co.elastic.logs/module: nginx
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
    networks:
      - echoapp
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.11.2
    container_name: filebeat
    environment:
      - ELASTICSEARCH_HOSTS=["${HOST_IP}:9200"]
      - KIBANA_HOST="${HOST_IP}:5601"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat-nginx.yml:/usr/share/filebeat/modules.d/nginx.yml:ro
    user: root
    networks:
      - echoapp
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.11.2
    container_name: metricbeat
    # command: metricbeat -e -system.hostfs=/hostfs -strict.perms=false
    environment:
      - ELASTICSEARCH_HOSTS=["${HOST_IP}:9200"]
      - KIBANA_HOST="${HOST_IP}:5601"
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./metricbeat-system.yml:/usr/share/metricbeat/modules.d/system.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    user: root
    networks:
      - echoapp
networks:
  echoapp:
    driver: bridge