filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      # templates:
      #   - condition.contains:
      #       docker.container.name: app
      #     config:
      #       - type: docker
      #         containers.ids:
      #           - "${data.docker.container.id}"
      #         pipeline: my-custom-pipeline

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup:
  kibana.host: "${KIBANA_HOST:kibana:5601}"
  dashboards.enabled: true